version: "3.9" 

services: 
  app: 
    image: xoderockson/xgame-api:latest 
    container_name: xgame-api 

    env_file:
      - .env 
    ports: 
      - 3001:3001 
    volumes:
      - /home/pc/var/app/blurr/.env:/usr/src/app/.env 
